### ISSUE TITLE
ActiveModel::UnknownAttributeError: unknown attribute 'variable_1' for Experiment.

### ISSUE THREAD

**Issue by Lixinyoung** [UCSF-MS-DCC/TopoDB#26]
Hello, 
For the sake of managing mouse colony, I tried to deploy your designed TopoDB on my local service. I met following error and I have no idea how to solve it:
`rails db:seed`
`rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'variable_1' for Experiment.
/home/duan/TopoDB/db/seeds.rb:116:in `block in <top (required)>'
/home/duan/TopoDB/db/seeds.rb:106:in `times'
/home/duan/TopoDB/db/seeds.rb:106:in `<top (required)>'
/home/duan/TopoDB/bin/rails:9:in `<top (required)>'
/home/duan/TopoDB/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)`
I am not sure that if it is the seeds.rb problem or my ruby-server porblem.
Any suggestion would be thankful!

**Comment by gaoywang** [comment]
me too, exactly the same issue!
